services:
  auth-db:
    container_name: auth-db
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD    
    networks:
      - my_net
    expose:
      - "$POSTGRES_PORT"
    ports:
      - "$POSTGRES_PORT:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-redis:
    container_name: auth-redis
    image: redis:latest
    networks:
      - my_net
    ports:
      - "$REDIS_PORT:$REDIS_PORT"
    restart: always

  auth-app:
    container_name: auth-app
    image: auth-app:latest
    depends_on:
      - auth-db
      - auth-redis
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "$APP_PORT:$APP_PORT"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-app.rule=Host(`yourdomain.com`)"
      - "traefik.http.services.fastapi-app.loadbalancer.server.port=8000"
    networks:
      - my_net
    restart: unless-stopped
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://auth-app:$APP_PORT/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  auth-traefik:
    image: traefik:v3.1
    container_name: auth-traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - my_net

networks:
    my_net:
        driver: bridge

volumes:
  postgres_data:
